### ISSUE TITLE
Will feedback on electric thrusters be updated in the future?

### ISSUE THREAD

**Issue by 517002650** [niklasberlin/MIDICRAFT_extended_LED_Feedback#6]
Does this plugin support feedback for electric thrusters? I hope to update the feedback for thrusters and push rods

**Comment by niklasberlin** [comment]
This Plugin is for Midicraft Controllers only and they do not have motorized faders, as this is not a general feedback plugin I will not add functionalities for other controllers but you can fork the code and make the necessary changes there. 
Keep in mind that this plugin contains some code that is super specific to the midicraft controllers (for example mapping the color to the right midi message) so it might be more useful to use this plugin as inspiration rather as a base for your own plugin
